### ISSUE TITLE
dirsrv_starttls_early is undefined

### ISSUE THREAD

**Issue by neilmunday** [lvps/389ds-replication#2]
When running the role as a consumer, the `dirsrv_starttls_early` value is reported as undefined.

Is the README correct as `dirsrv_use_starttls` is not referenced by any tasks of the role.

**Comment by lvps** [comment]
I probably got the two variables mixed up - `dirsrv_starttls_early` comes from my [other role](https://github.com/lvps/389ds-server), so if you use both at the same time it should still work, but in this role it should be `dirsrv_use_starttls` instead.

The "early" part is there because the other role may connect to 389DS before setting up TLS, then configuring it and later connecting via TLS, so "early" it doesn't use TLS but later does. In this role there should be only one option: use TLS or not, so `dirsrv_use_starttls`.

I will investigate further and hopefully fix this tomorrow, or you can create a PR: if you test it and it works, it's good for me

**Comment by neilmunday** [comment]
I set `dirsrv_starttls_early` in my playbook and that got the role to work. Thanks for the quick response.

I suspect `sed -r -i 's/dirsrv_starttls_early/dirsrv_use_starttls/g' ./*` should do the trick ;-)

**Comment by lvps** [comment]
Yep, that was a very simple fix. I've released an updated version now.
Thanks for reporting this issue!

**Comment by neilmunday** [comment]
Thanks for fixing the issue - glad it was a simple one!
